#!/usr/bin/env node

// $0 is the first argument of the command line
var argv = require('yargs')
  // Show on Usage:
  .usage('Usage: $0 <command> [options]')
  // Show on Commands:
  .command('count', 'Count the lines in a file')
  // Show on Examples:
  .example('$0 count -f foo.js', 'count the lines in the given file')
  .example('$0 count --file foo.js', 'count the lines in the given file')
  .alias('f', 'file')
  .nargs('f', 1)
  .describe('f', 'Load a file')
  .demandOption(['f'])
  .help('h')
  .alias('h', 'help')
  .epilog('copyright 2018')
  .argv;

var fs = require('fs');
var s = fs.createReadStream(argv.file);

var lines = 0;
s.on('data', function (buf) {
  lines += buf.toString().match(/\n/g).length;
});

s.on('end', function () {
  console.log(lines);
});
